name: TTLock2MQTT
version: "0.3.3.2"
slug: ttlock2mqtt
description: Connection between TTLock devices with Home Assistant using MQTT
url: "https://github.com/TenySmart/TTLock2MQTT"
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
services:
  - "mqtt:need"
options:
  Scan_interval: 60
  Log_level: "INFO"
schema:
  TTLock_username: str
  TTLock_password: "password"
  TTLock_client_Id: str
  TTLock_client_secrect: str
  Scan_interval: "int(10,3600)"
  Log_level: "list(DEBUG|INFO|WARNING|ERROR)"